from typing import Protocol

from workflow_engine.application.dto import RunStatusDTO, TaskRequestDTO, TaskResultDTO, TokenDTO
from workflow_engine.domain.model import Definition
from workflow_engine.domain.value_objects import RunId, TokenId


class Runner(Protocol):
    def run(self, request: TaskRequestDTO) -> TaskResultDTO: ...


class Clock(Protocol):
    def now_epoch(self) -> float: ...


class WorkflowStore(Protocol):
    def save_definition(self, definition: Definition) -> str: ...
    def create_run(
        self, definition_hash: str, inputs: tuple[tuple[str, str], ...], key: str | None = None
    ) -> RunId: ...
    def definition_for_run(self, run_id: RunId) -> Definition: ...
    def inputs_for_run(self, run_id: RunId) -> tuple[tuple[str, str], ...]: ...
    def outputs_for_run(self, run_id: RunId) -> tuple[tuple[str, str], ...]: ...
    def status(self, run_id: RunId) -> RunStatusDTO: ...
    def next_ready(self, run_id: RunId) -> TokenDTO | None: ...
    def waiting_tokens(self, run_id: RunId) -> tuple[TokenDTO, ...]: ...
    def token(self, token_id: TokenId) -> TokenDTO: ...
    def claim(self, token: TokenDTO) -> TokenDTO | None: ...
    def move(
        self,
        token: TokenDTO,
        outcome: str,
        target: str,
        max_visits: int | None,
        output_name: str | None = None,
        output: str = "",
    ) -> bool: ...
    def fork(
        self,
        token: TokenDTO,
        join: str,
        branches: tuple[tuple[str, str], ...],
        limits: tuple[tuple[str, int | None], ...],
    ) -> bool: ...
    def arrive_join(
        self,
        token: TokenDTO,
        success_target: str,
        failure_target: str,
        success_limit: int | None,
        failure_limit: int | None,
    ) -> bool: ...
    def wait_for_input(self, token: TokenDTO) -> bool: ...
    def submit_input(
        self, token: TokenDTO, outcome: str, target: str, limit: int | None
    ) -> bool: ...
    def end(self, token: TokenDTO, result: str) -> bool: ...
    def quota_wait(self, token: TokenDTO, wake_at: float) -> bool: ...
    def wake_due(self, now: float) -> int: ...
    def mark_attention(self, token: TokenDTO) -> None: ...
    def recover_inflight(self, run_id: RunId) -> int: ...
