from typing import Protocol, runtime_checkable

from workflow_engine.application.dto import (
    ChannelCommandDTO,
    NotificationDTO,
    RunStatusDTO,
    ScheduleDTO,
    TaskRequestDTO,
    TaskResultDTO,
    TokenDTO,
)
from workflow_engine.domain.model import Definition, TimerTrigger
from workflow_engine.domain.value_objects import ArtifactRef, RunId, TokenId


@runtime_checkable
class Runner(Protocol):
    def run(self, request: TaskRequestDTO) -> TaskResultDTO: ...


class Clock(Protocol):
    def now_epoch(self) -> float: ...


class DefinitionCatalog(Protocol):
    def get(self, definition_id: str) -> Definition: ...


class ActorPolicy(Protocol):
    def permits(self, command: ChannelCommandDTO) -> bool: ...


class ChannelAccessStore(Protocol):
    def bind_channel(
        self, run_id: RunId, source: str, actor_id: str, channel_id: str | None
    ) -> None: ...
    def can_access(self, run_id: RunId, source: str, actor_id: str) -> bool: ...


class NotificationStore(Protocol):
    def pending_notifications(self) -> tuple[NotificationDTO, ...]: ...
    def mark_notification_sent(self, notification_id: str) -> bool: ...


class NotificationSender(Protocol):
    def send(self, notification: NotificationDTO) -> None: ...


class ArtifactStore(Protocol):
    def put_text(self, text: str) -> ArtifactRef: ...


class NextFire(Protocol):
    def after(self, cron: str, timezone: str, epoch: float) -> float: ...


class ScheduleStore(Protocol):
    def register_timer(
        self, definition_hash: str, index: int, timer: TimerTrigger, due_at: float
    ) -> None: ...
    def due_schedules(self, now: float) -> tuple[ScheduleDTO, ...]: ...
    def fire_schedule(self, schedule: ScheduleDTO, next_at: float) -> RunId | None: ...


class WorkflowStore(Protocol):
    def save_definition(self, definition: Definition) -> str: ...
    def create_run(
        self, definition_hash: str, inputs: tuple[tuple[str, str], ...], key: str | None = None
    ) -> RunId: ...
    def definition_for_run(self, run_id: RunId) -> Definition: ...
    def inputs_for_run(self, run_id: RunId) -> tuple[tuple[str, str], ...]: ...
    def outputs_for_run(self, run_id: RunId) -> tuple[tuple[str, str], ...]: ...
    def status(self, run_id: RunId) -> RunStatusDTO: ...
    def next_ready(self, run_id: RunId) -> TokenDTO | None: ...
    def ready_run_ids(self) -> tuple[RunId, ...]: ...
    def waiting_tokens(self, run_id: RunId) -> tuple[TokenDTO, ...]: ...
    def token(self, token_id: TokenId) -> TokenDTO: ...
    def claim(self, token: TokenDTO) -> TokenDTO | None: ...
    def move(
        self,
        token: TokenDTO,
        outcome: str,
        target: str,
        max_visits: int | None,
        output_name: str | None = None,
        output: str = "",
        artifact: ArtifactRef | None = None,
    ) -> bool: ...
    def fork(
        self,
        token: TokenDTO,
        join: str,
        branches: tuple[tuple[str, str], ...],
        limits: tuple[tuple[str, int | None], ...],
    ) -> bool: ...
    def arrive_join(
        self,
        token: TokenDTO,
        success_target: str,
        failure_target: str,
        success_limit: int | None,
        failure_limit: int | None,
    ) -> bool: ...
    def wait_for_input(self, token: TokenDTO, prompt: str) -> bool: ...
    def wait_for_host(self, token: TokenDTO) -> bool: ...
    def host_waiting(self) -> tuple[TokenDTO, ...]: ...
    def claim_host(self, token: TokenDTO) -> TokenDTO | None: ...
    def submit_input(
        self, token: TokenDTO, outcome: str, target: str, limit: int | None
    ) -> bool: ...
    def end(self, token: TokenDTO, result: str) -> bool: ...
    def quota_wait(self, token: TokenDTO, wake_at: float, external_id: str | None) -> bool: ...
    def wake_due(self, now: float) -> int: ...
    def mark_attention(self, token: TokenDTO) -> None: ...
    def recover_inflight(self, run_id: RunId) -> int: ...
    def recover_expired_inflight(self, now: float) -> int: ...
    def renew_lease(self, token_id: TokenId) -> bool: ...
